### PR TITLE
fix check_version requiring minimum python version as 3.7 due to capture_output arg

### PR DESCRIPTION
**Pull request by manisnesan**
Adds a fix for https://github.com/muellerzr/dependency_checker/issues/6. This also includes installing specific pip version since the test (assert) validates this. And should fix the CI build

### CODE REVIEW

**Comment by manisnesan** [comment]
@muellerzr - Added the fix and also few additional changes. Let me know what you think.

**Comment by muellerzr** [comment]
Why are we wanting a specific pip version too, along with python? (Sorry, not quite following the correlation here)

**Comment by manisnesan** [comment]
> Why are we wanting a specific pip version too, along with python? (Sorry, not quite following the correlation here)

@muellerzr - I noticed this where the below code is checking for specific pip dependency package. This will fail if someone does not have the same pip version installed.  This is the reason ( I was having pip with a different version and the cell was failing for me). 

`assert deps == {'pipdeptree':'2.1.0', 'pip':'21.2.4'}`

**Comment by muellerzr** [comment]
Ah. That's actually an issue with the test I wrote then. That test should be changed to just have `pipdeptree`. As a specific pip version isn't needed. 

As a result, that's a faulty test of mine :) 

(Not sure there *is* a decent way to check for that, will need to think on it)

**Comment by muellerzr** [comment]
if you remove the pin, I'll go ahead and merge and fix that test.

**Comment by manisnesan** [comment]
> That's actually an issue with the test I wrote then. That test should be changed to just have pipdeptree. As a specific pip version isn't needed.

Agreed. 

> if you remove the pin, I'll go ahead and merge and fix that test.

@muellerzr Yes. Will do and submit a fix.

**Comment by manisnesan** [comment]
@muellerzr Changes submitted based on your review comment.

**Review by muellerzr — APPROVED** [review]
LG2M, thanks Mani!

**Pull request merged**
